name: devitofwi
channels:
  - defaults
  - conda-forge
  - numba
dependencies:
  - python
  - pip
  - numpy
  - scipy
  - matplotlib
  - tqdm
  - pylops
  - pyproximal
  - ipython
  - jupyter
  - pytest
  - pip:
    - devito==4.8.3